config/routes.rb
Rails.application.routes.draw do
 resources :kittens
 root 'kittens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end
  
  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Congragulations You have created a kitten"
      redirect_to root_url 
    end
  end
  
  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kitten }
      format.json { render :json => @kitten }
    end
  end

  def update
    @kitten = Kitten.find(params[:id]) 
    if @kitten.update(kitten_params)
      flash[:success] = "You Have Edited Your Kitten"
      redirect_to root_url
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    if @kitten.destroy
      flash[:success] = "Kitten is destroyed :("
      redirect_to root_url 
    end
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :age %><br />
      <%= f.number_field :age %>
    </p>
    <p>
      <%= f.label :cuteness %><br />
      <%= f.number_field :cuteness %>
    </p>
    <p>
      <%= f.label :softness %><br />
      <%= f.number_field :softness %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render 'form' %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<% @kittens.each do |kitten| %>
    <h3> <%= kitten.name %> </h3>
    <p> Age: <%= kitten.age %> <span> <%= link_to "show", kitten_path(kitten) %> </span>
    <span> <%= link_to "edit", edit_kitten_path(kitten) %> </span>
    <span> <%= link_to "delete", kitten_path(kitten), method: :delete, 
    data: {confirm: "Really delete the article?"} %> </span>
    </p> 
    <p> Cuteness: <%= kitten.cuteness %> </p>
    <p> Softness: <%= kitten.softness %></p>
<% end %>
<%= link_to "Create New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Crete New Kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1> <%= @kitten.name %> </h1>
<p> Age: <%= @kitten.age %> <span> <%= link_to "show all kittens", kittens_path %> </span>
<span> <%= link_to "edit", edit_kitten_path(@kitten) %> </span>
<span> <%= link_to "delete", kitten_path(@kitten), method: :delete, 
data: {confirm: "Really delete the article?"} %> </span>
</p> 
<p> Cuteness: <%= @kitten.cuteness %> </p>
<p> Softness: <%= @kitten.softness %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
    <%= yield %>
  </body>
</html>